In [1]:
# Numpy
import numpy as np
calls=np.array([5,7,8,9,11])
print(calls)



[ 5  7  8  9 11]


In [4]:
a=np.array([["Jan","Feb","March"],
            [300,400,700],
            [4,5,6],
            [200,500,600]])
print(a)
print(a.shape)


[['Jan' 'Feb' 'March']
 ['300' '400' '700']
 ['4' '5' '6']
 ['200' '500' '600']]
(4, 3)


In [ ]:
#Array Indexing
a=np.array([["Jan","Feb","March"],
            [300,400,700],
            [4,5,6],
            [200,500,600]])

print(a[0])


['Jan' 'Feb' 'March']


In [12]:
a=np.array([["Jan","Feb","March"],
            [300,400,700],
            [4,5,6],
            [200,500,600]])
print(a[2][2])
print(a[1,:])
print(a[:,1])
print(a[1:,2])
print(a[2:,1])
print(a[2,1])


6
['300' '400' '700']
['Feb' '400' '5' '500']
['700' '6' '600']
['5' '500']
5


In [ ]:
#Boolean Filtering
s_r=np.array([3.6,4,2,3,1])
print(s_r[s_r>3])
print(s_r)

[3.6 4. ]
[3.6 4.  2.  3.  1. ]


In [17]:
s_r=np.array([3.6,4,2,3,1])
print([s_r>3])
print(s_r[s_r>=2])

[array([ True,  True, False, False, False])]
[3.6 4.  2.  3. ]


In [24]:
s_r=np.array([3.6,4,2,3,1,7,9])
f=(s_r>=2) & (s_r<=4)
print(s_r[f])

[3.6 4.  2.  3. ]


In [47]:
a=np.array([["Jan","Feb","March"],
            [300,400,700],
            [4,5,6],
            [200,500,600]])
print(a[1:,:])
print(np.sum((a[1:,:].astype('int'))))
print(np.mean((a[1:,:].astype('int')))) #Average
print(np.max((a[1:,:].astype('int'))))
print(np.min((a[1:,:].astype('int'))))
print(np.std((a[1:,:].astype('int'))))






[['300' '400' '700']
 ['4' '5' '6']
 ['200' '500' '600']]
2715
301.6666666666667
700
4
251.89327546050572


In [52]:
North=np.array([3,4,5])
South=np.array([6,6,7])
np.concatenate((North,South))


array([3, 4, 5, 6, 6, 7])

In [54]:
np.add(North,South)

array([ 9, 10, 12])

In [55]:
np.concatenate(((North,South)))

array([3, 4, 5, 6, 6, 7])

In [57]:
np.subtract(North,South)

array([-3, -2, -2])

In [59]:
np.divmod(North,South)

(array([0, 0, 0]), array([3, 4, 5]))

In [73]:
a=np.array([["Jan","Feb","March"],
            [300,400,700],
            [4,5,6]])
print(np.sum(a[1:,0].astype('int')))
print((np.sum(a[1:,0].astype('int'))))
print(np.sum(a[1:,2].astype('int')))


304
304
706


In [ ]:
a=np.array([["Jan","Feb","March"],
            [300,400,700],
            [4,5,6]])
print(np.sum(a[1:,:].astype('int'),axis=0)) #column-wise


[304 405 706]


In [ ]:
a=np.array([["Jan","Feb","March"],
            [300,400,700],
            [4,5,6]])
print(np.sum(a[1:,:].astype('int'),axis=1)) #Row-wise


[1400   15]


In [4]:
#Split
a=np.array([40,80,50,20,30])
print(np.array_split(a,3))
print(np.array_split(a,4))

[array([40, 80]), array([50, 20]), array([30])]
[array([40, 80]), array([50]), array([20]), array([30])]


In [7]:
import numpy as np
cd=np.array([132,13,15,102])
np.where(cd==15)

(array([2]),)

In [8]:
import numpy as np
cd=np.array([132,13,15,102])
cd[np.where(cd==15)]

array([15])

In [18]:
import numpy as np
CID=np.array(['c101','c102','c103','c104'])
Rating=np.array([2,3,4.3,2])
print(np.where(CID=='c103'))
print(Rating[np.where(CID=='c103')])
print(np.max(Rating))
print(np.sort(Rating)[::-1])
print(CID[np.where(Rating==4.3)])





(array([2]),)
[4.3]
4.3
[4.3 3.  2.  2. ]
['c103']


In [22]:
import numpy as np
CID=np.array(['c101','c102','c103','c104'])
Rating=np.array([2,3,4.3,2])
print(Rating*1.1)

[2.2  3.3  4.73 2.2 ]


In [ ]:
call_duration=np.array([5,7,10,15,6,9,12,8])
satisfaction=np.array([5,4,3,5,2,4,5,3])
calls=np.array([120,130,160,180,150,170,140,200])

print("average:",np.mean(call_duration))
print("maximum:",np.max(satisfaction))
print("calls greater than 150:",calls[calls>150])
print("sort:",np.sort(call_duration))
print("search:",np.where(satisfaction==5))
print(" Increase call duration by 10%:",(call_duration*1.1))
print("combine two call datasets:",np.concatenate((call_duration,calls)))
print("split monthly data:",np.array_split(call_duration,6))
print("First Five Records:",)


average: 9.0
maximum: 5
calls greater than 150: [160 180 170 200]
sort: [ 5  6  7  8  9 10 12 15]
search: (array([0, 3, 6]),)
 Increase call duration by 10%: [ 5.5  7.7 11.  16.5  6.6  9.9 13.2  8.8]
combine two call datasets: [  5   7  10  15   6   9  12   8 120 130 160 180 150 170 140 200]
split monthly data: [array([5, 7]), array([10, 15]), array([6]), array([9]), array([12]), array([8])]
